# sc-nfs.yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  ## If nfs-storageclass-name is not null, use the TF vars input value, otherwise use the default value
  #name: ${ coalesce(nfs-storageclass-name, "nfs-csi") }
  #name: ${ nfs-storageclass-name != null ? nfs-storageclass-name : "nfs-csi" }
  name: ${nfs-storageclass-name}
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.10
  share: /volume2/Data/Kubernetes/nfs_volume_data_miniws
reclaimPolicy: Delete             # Retain, Delete
volumeBindingMode: Immediate      # Immediate, WaitForFirstConsumer
mountOptions:
  - hard
  - nfsvers=4.0
#allowVolumeExpansion: true